-- PTT Popular Boards Seed SQL
INSERT OR IGNORE INTO boards (name, display_name, is_popular, is_verified) VALUES
('AC_In', '◎[裏洽]', 1, 1),
('AI_Art', '◎AI藝術與生成板 AIGC歡迎來聊!', 1, 1),
('ALLPOST', '◎跨板式LOCAL新文章', 1, 1),
('AllTogether', '◎[歐兔] I potato U ♥', 1, 1),
('Audiophile', '◎[喇音] 注意 Line 加好友詐騙', 1, 1),
('Aviation', '◎[航空] 航空板', 1, 1),
('BabyMother', '◎[寶寶] 記得打流感疫苗', 1, 1),
('BabyProducts', '◎防詐騙，交易異常時，自行找客服', 1, 1),
('Bank_Service', '◎[銀行服務板]', 1, 1),
('Baseball', '棒球', 1, 1),
('BaseballXXXX', '◎[四叉] 溫馨提醒 記得看板規喔', 1, 1),
('basketballTW', '◎[台籃] 例行賽', 1, 1),
('Beauty', '◎[表特] 貼AI圖 一律水桶+退文', 1, 1),
('bicycle', '◎[單車] 騎車注意交通安全', 1, 1),
('biker', '◎[機車] 新年快樂', 1, 1),
('BikerShop', '◎機車相關買賣板‧一天限發一篇文', 1, 1),
('Boy-Girl', '◎[男女] 歡迎光臨男女板', 1, 1),
('Broad_Band', '◎[寬頻板] 禁發廣告文/轉讓文', 1, 1),
('C_Chat', '希洽', 1, 1),
('Car', '汽車', 1, 1),
('CarShop', '◎沒出廠月份，水桶30天', 1, 1),
('cat', '◎禁止贈送徵求醫療用品過期食品', 1, 1),
('CFantasy', '◎[玄幻] 年度推書活動心得文徵文中', 1, 1),
('CheerGirlsTW', '◎[真香] 阿金請勿發表不當言論', 1, 1),
('Chiayi', '◎[嘉義] 鄉民宴因場地延期明年初', 1, 1),
('China-Drama', '◎[中劇] 讓空降來得更猛烈些吧！', 1, 1),
('CN_Entertain', '◎[中綜]  乘風破浪 歌手馬來西亞', 1, 1),
('Coffee', '◎咖啡 秋意漸濃', 1, 1),
('creditcard', '◎[卡板]', 1, 1),
('CVS', '◎[CVS] 超商店員a.k.a.superman', 1, 1),
('DC_SALE', '◎詐騙請去至底文回覆', 1, 1),
('DIABLO', '◎[暗黑] D4 s12新賽季', 1, 1),
('Digitalhome', '◎[電視] 新年買新電視', 1, 1),
('DMM_GAMES', '◎[DMMG] 日幣匯率低 課金好時機', 1, 1),
('Drama-Ticket', '◎藝文票券轉售板 禁止徵票小心詐騙', 1, 1),
('DSLR', '◎[攝影] 2026', 1, 1),
('E-appliance', '◎[家電] 發文請照規定發文', 1, 1),
('e-coupon', '◎新板主2025年4月25日上任', 1, 1),
('e-shopping', '◎[ＥＳ] 注意板規 遠離水桶', 1, 1),
('EAseries', '◎[EA] 歐美影集板', 1, 1),
('EatToDie', '◎[飽板] 能吃就是福', 1, 1),
('Elephants', '◎[兄弟] 中信兄弟年度口號『奪還』', 1, 1),
('FAPL', '◎歡樂．三喵．足球', 1, 1),
('fastfood', '◎[速食] 慟！麥香魚起士只放半片', 1, 1),
('FATE_GO', '◎[FGO] 台 龍宮城 / 日 那個日子', 1, 1),
('Food', '◎美食板', 1, 1),
('Foreign_Inv', '◎[海投] 噓文全面解禁', 1, 1),
('FORMULA1', '◎F1板', 1, 1),
('Gamesale', '二手遊戲', 1, 1),
('give', '◎[贈送] 標題不合置底文規定  刪', 1, 1),
('Gossiping', '八卦', 1, 1),
('Guardians', '◎[悍將] 2026賽季開幕「不一樣了！', 1, 1),
('H-GAME', '◎H-GAME板', 1, 1),
('HardwareSale', '硬體買賣', 1, 1),
('HatePolitics', '◎[政黑] 當我們同在17，在17在17', 1, 1),
('Headphone', '◎[耳機] 徵文目錄&注意交易資格', 1, 1),
('Hearthstone', '◎[爐石] 《浩劫與重生》', 1, 1),
('Hinatazaka46', '◎日向坂46', 1, 1),
('home-sale', '◎[房版] 請詳閱新板規避免違規', 1, 1),
('Hsinchu', '◎[新竹] 新版規研議中~~\⊙▽⊙/', 1, 1),
('iOS', '蘋果', 1, 1),
('Japan_Travel', '◎櫻花旺季要注意春之嵐這種惡天候', 1, 1),
('japanavgirls', '◎AV女優板 清新、優質,神人照格式', 1, 1),
('Japandrama', '◎[日劇] 夏秋日21 VIVANT', 1, 1),
('joke', '◎[就可]', 1, 1),
('Kaohsiung', '◎シュワッチ！Shuwatch!', 1, 1),
('Key_Mou_Pad', '◎[鍵鼠] 2026新年快樂', 1, 1),
('KoreaDrama', '◎[韓劇]', 1, 1),
('KoreaStar', '◎[韓星] 友善追星 你我有責', 1, 1),
('KR_Entertain', '◎[韓綜] Show Me The 新板主!', 1, 1),
('Lakers', '◎[Lakers] 25-26 SEASON', 1, 1),
('LifeIsMoney', '省錢', 1, 1),
('Lions', '◎[獅隊] 中職37年亞太主場開打！', 1, 1),
('LoL', '◎[LoL] MingLee', 1, 1),
('MacShop', '◎[麥蝦] 禁止販售非現貨商品', 1, 1),
('Marginalman', '◎[鳴潮] 新番推薦：冰之城牆', 1, 1),
('marriage', '◎[婚姻] 歡迎光臨婚姻板', 1, 1),
('marvel', '◎[媽佛] 你吃了誰煮的麵', 1, 1),
('miHoYo', '◎[米哈游] 星穹鐵道4.1 不死途 PU', 1, 1),
('Military', '◎[軍事]理性討論軍事 請詳閱板規', 1, 1),
('MLB', '◎[MLB] 2026賽季/請注意詐騙訊息', 1, 1),
('MobileComm', '◎[通訊] 手機o平板o資費 請進!', 1, 1),
('MobilePay', '◎刷卡回饋問題請至信用卡板', 1, 1),
('mobilesales', '◎[Mobile] 遵守版規，進桶看通知信', 1, 1),
('model', '◎這裡是Ptt模型板～拍賣日為週六', 1, 1),
('movie', '電影', 1, 1),
('MRT', '◎[捷運] 即日起嚴格抓AI文', 1, 1),
('MuscleBeach', '◎[健身] 發文前請務必詳閱板規', 1, 1),
('nb-shopping', '◎[筆電蝦]', 1, 1),
('NBA', '籃球', 1, 1),
('NSwitch', '◎[NS] 耀西與不可思議的圖鑑 5/21', 1, 1),
('ONE_PIECE', '◎[海賊王] 1178 "惡夢漸醒"', 1, 1),
('part-time', '◎[打工] 不看板規發文我就劣退水桶', 1, 1),
('PathofExile', '◎[PoE] 流亡黯道二代 啟動！', 1, 1),
('PC_Shopping', '電蝦', 1, 1),
('PlayStation', '◎[PS5] 春季特賣開跑', 1, 1),
('PokemonGO', '◎[PMGO] 2026台北花伴野餐在安森唷', 1, 1),
('PublicServan', '◎[公職]', 1, 1),
('PuzzleDragon', '◎[P＆D] 偶像大師 灰姑娘女孩 合作', 1, 1),
('Railway', '◎[鐵道] 台鐵螺絲跟737 MAX 9同款?', 1, 1),
('Road_Running', '◎跑步版-比賽季開跑啦', 1, 1),
('SakaTalk', '◎坂道閒聊板', 1, 1),
('sex', '◎[西斯] 愛對了人 情人節每天都過', 1, 1),
('Soft_Job', '◎[軟工] 成為全宇宙のNo.1吧', 1, 1),
('SportLottery', '◎[運彩] 4/1~4/7 板主徵選投票中', 1, 1),
('Steam', '◎本板禁止買賣合購代購代刷', 1, 1),
('Stock', '股票', 1, 1),
('studyteacher', '◎實習教師! 看板規!代理置底推!^0^', 1, 1),
('SuperBike', '◎PTT重機板 ~ 發買賣文請詳閱置底', 1, 1),
('tabletennis', '◎12:30四強 林昀儒 世界盃4/5', 1, 1),
('TaichungBun', '◎[台中] 板規修改投票中 請按V投票', 1, 1),
('Tainan', '◎[台南]', 1, 1),
('TaiwanDrama', '◎[臺劇] 二代咖啡館的化外接班人', 1, 1),
('Talent', '◎[天才衝衝衝] 金馬奔騰衝破新紀元', 1, 1),
('Teacher', '◎[踢雀] 立春正月', 1, 1),
('Tech_Job', '◎[科技]', 1, 1),
('Tennis', '◎[網球] 絕代雙驕之最年輕滿貫盟主', 1, 1),
('TW_Entertain', '◎[台綜] 恭喜LULU，漢典', 1, 1),
('TY_Research', '◎恭喜鳳凰成為58年首個11月登陸颱', 1, 1),
('Vtuber', '◎[Vtuber] 4/4 馬車World團體賽', 1, 1),
('Wanted', '◎[汪踢] I Want U', 1, 1),
('watch', '◎[錶板] Show me your Watch!', 1, 1),
('WCDragons', '◎[味全龍]', 1, 1),
('WomenTalk', '◎[女孩] 天氣冷小心保暖', 1, 1),
('WOW', '◎[WoW] 副本懶人包 #1fnH-x6v', 1, 1),
('Wuther-Waves', '◎[鳴潮] 3.2 於影中啟明的決心', 1, 1),
('YuanChuang', '◎[原創] 通靈大師法力無邊～', 1, 1),
('YUGIOH', '◎[遊戲王] Master Duel  變換舞夜', 1, 1);