export {
  upsertUser,
  getUserById,
  getSubscriptionsByUser,
  getSubscriptionCount,
  getUserCounts,
  createSubscription,
  deleteSubscription,
  getSubscriptionByUserAndBoard,
  createSubscriptionFilter,
  getSubscriptionFilter,
  updateSubscriptionFilter,
  getPopularBoards,
  getAllBoards,
  searchBoards,
  upsertBoard,
  updateBoardSnapshot,
  getActiveBoardsWithSubscribers,
  fetchNextPendingCrawlBoard,
  markCrawlJobDone,
  enqueuePendingNotifications,
  enqueueReplyNotifications,
  fetchPendingNotificationsWithUser,
  updateNotificationStatuses,
  updateAdUnlockedAt,
  getActivePostWatches,
  getPostWatchesByUser,
  getPostWatchCount,
  deletePostWatch,
  updatePostWatchResult,
  markPostWatchQueueDone,
  claimPostWatchQueueJob,
  type SubscriptionWithRank,
  type NotificationInsert,
  type NotificationStatusUpdate,
  type PendingNotificationWithUser,
} from '../../../bot/src/db/queries'
