export {
  upsertUser,
  getUserById,
  getSubscriptionsByUser,
  getSubscriptionCount,
  createSubscription,
  deleteSubscription,
  getSubscriptionByUserAndBoard,
  createSubscriptionFilter,
  getPopularBoards,
  searchBoards,
  upsertBoard,
  updateBoardSnapshot,
  getActiveBoardsWithSubscribers,
  fetchNextPendingCrawlBoard,
  markCrawlJobDone,
  enqueuePendingNotifications,
  fetchPendingNotificationsWithUser,
  updateNotificationStatuses,
  updateAdUnlockedAt,
  type SubscriptionWithRank,
  type NotificationInsert,
  type NotificationStatusUpdate,
  type PendingNotificationWithUser,
} from '../../../bot/src/db/queries'
