export const CONFIG = {
  FREE_BOARDS_LIMIT: 2,
  AD_UNLOCK_DURATION: 86400,
  FREE_KEYWORDS_PER_BOARD: 1,
  MAX_KEYWORDS_PER_BOARD: 5,
  MAX_CRAWL_WORKERS: 1,
  CRAWL_MAX_RUNTIME: 4 * 3600,
  CRAWL_JOB_TIMEOUT: 30,
  CRAWL_LOCK_TIMEOUT: 300,
  NOTIFICATION_BATCH_SIZE: 50,
  NOTIFICATION_RETRY_MAX: 3,
  CLEANUP_DAYS: 7,
}
